# Generated by Django 3.0 on 2020-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('fid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('fdesignation', models.CharField(max_length=50)),
                ('fjoin_date', models.CharField(max_length=50)),
                ('fqualification', models.CharField(max_length=10)),
                ('fgender', models.CharField(max_length=10)),
                ('fmobile', models.IntegerField()),
                ('femail', models.EmailField(max_length=100)),
                ('fbatch', models.CharField(max_length=10)),
                ('fblood', models.CharField(max_length=10)),
                ('fdob', models.DateField()),
                ('faddress', models.CharField(max_length=200)),
                ('fpassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sadd_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('srollno', models.IntegerField()),
                ('squalification', models.CharField(max_length=10)),
                ('sgender', models.CharField(max_length=10)),
                ('fbatch', models.CharField(max_length=10)),
                ('sdob', models.DateField()),
                ('sadd_date', models.DateField()),
                ('sblood', models.CharField(max_length=10)),
                ('smobile', models.IntegerField()),
                ('semail', models.EmailField(max_length=100)),
                ('saddress', models.CharField(max_length=200)),
                ('spassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
